---
- hosts : all
  become: true
  tasks :
  - name: Updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : stop previous docker container 
    command : docker stop arman

  - name : remove stopped container   
    command : docker rm -f arman
    
  - name : remove docker image   
    command : docker image  rm -f arman23/insureproject:1.0
    
  - name: Deploy Docker Container
    command: docker run -itd --name arman -p 8084:8081 arman23/insureproject:1.0
