---
- hosts : all
  become: true
  tasks :
  - name: Updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : stop previous docker container 
    command : docker stop arman

  - name : rename docker dontainer 
    command : docker rename arman arman
    
  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 arman23/insureproject:1.0
